import { Product } from "./types";

// Datos semilla (sección 7 de claude.md).
// Incluye un producto con stock bajo (WHEY-VAN) y uno agotado (PRE-BLUE).
// Los 8 primeros son suplementos/accesorios: se venden en ambos canales.
// Los últimos 10 son la línea "Comidas": platillos preparados, EXCLUSIVOS
// de la tienda en línea (no aparecen en el POS).
export const SEED_PRODUCTS: Product[] = [
  {
    id: "p1",
    sku: "WHEY-CHO",
    barcode: "7501000000011",
    name: "Proteína Whey Chocolate",
    category: "Proteínas",
    emoji: "🥤",
    price: 650,
    stock: 12,
    minStock: 5,
    channels: ["online", "fisica"],
    photoQuery: "chocolate protein shake",
  },
  {
    id: "p2",
    sku: "WHEY-VAN",
    barcode: "7501000000028",
    name: "Proteína Whey Vainilla",
    category: "Proteínas",
    emoji: "🥛",
    price: 650,
    stock: 3,
    minStock: 5,
    channels: ["online", "fisica"],
    photoQuery: "vanilla protein powder",
  },
  {
    id: "p3",
    sku: "CREA-300",
    barcode: "7501000000035",
    name: "Creatina Monohidratada",
    category: "Creatina",
    emoji: "⚪",
    price: 350,
    stock: 8,
    minStock: 5,
    channels: ["online", "fisica"],
    photoQuery: "creatine powder supplement",
  },
  {
    id: "p4",
    sku: "BAR-PROT",
    barcode: "7501000000042",
    name: "Barra de Proteína",
    category: "Snacks",
    emoji: "🍫",
    price: 45,
    stock: 40,
    minStock: 10,
    channels: ["online", "fisica"],
    photoQuery: "protein bar",
  },
  {
    id: "p5",
    sku: "PRE-BLUE",
    barcode: "7501000000059",
    name: "Pre-Entreno Blue",
    category: "Suplementos",
    emoji: "🧪",
    price: 520,
    stock: 0,
    minStock: 5,
    channels: ["online", "fisica"],
    photoQuery: "pre workout supplement",
  },
  {
    id: "p6",
    sku: "ELEC-500",
    barcode: "7501000000066",
    name: "Bebida Electrolitos",
    category: "Bebidas",
    emoji: "🧃",
    price: 38,
    stock: 25,
    minStock: 8,
    channels: ["online", "fisica"],
    photoQuery: "electrolyte sports drink",
  },
  {
    id: "p7",
    sku: "PB-500",
    barcode: "7501000000073",
    name: "Mantequilla de Maní",
    category: "Alimentos",
    emoji: "🥜",
    price: 180,
    stock: 6,
    minStock: 5,
    channels: ["online", "fisica"],
    photoQuery: "peanut butter jar",
  },
  {
    id: "p8",
    sku: "SHK-700",
    barcode: "7501000000080",
    name: "Shaker 700ml",
    category: "Accesorios",
    emoji: "🥤",
    price: 120,
    stock: 15,
    minStock: 5,
    channels: ["online", "fisica"],
    photoQuery: "protein shaker bottle",
  },

  // ── Línea "Comidas" — solo tienda en línea ──────────────────────────
  {
    id: "m1",
    sku: "MEAL-POLLO",
    barcode: "7501000000097",
    name: "Bowl de Pollo Teriyaki",
    category: "Comidas",
    emoji: "🍱",
    price: 145,
    stock: 20,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 520, protein: 42, minutes: 15, tags: ["30g+ Proteína", "Post-Entreno"] },
    photoQuery: "teriyaki chicken bowl",
  },
  {
    id: "m2",
    sku: "MEAL-SALM",
    barcode: "7501000000103",
    name: "Salmón con Quinoa",
    category: "Comidas",
    emoji: "🐟",
    price: 180,
    stock: 14,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 480, protein: 38, minutes: 20, tags: ["30g+ Proteína"] },
    photoQuery: "salmon quinoa bowl",
  },
  {
    id: "m3",
    sku: "MEAL-RES",
    barcode: "7501000000110",
    name: "Bowl de Res y Camote",
    category: "Comidas",
    emoji: "🥘",
    price: 160,
    stock: 18,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 560, protein: 45, minutes: 18, tags: ["30g+ Proteína", "Post-Entreno"] },
    photoQuery: "beef sweet potato bowl",
  },
  {
    id: "m4",
    sku: "MEAL-VEG",
    barcode: "7501000000127",
    name: "Buddha Bowl Vegano",
    category: "Comidas",
    emoji: "🥗",
    price: 130,
    stock: 22,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 410, protein: 24, minutes: 12, tags: ["Vegano", "Rápidas"] },
    photoQuery: "vegan buddha bowl",
  },
  {
    id: "m5",
    sku: "MEAL-PAV",
    barcode: "7501000000134",
    name: "Wrap de Pavo Fit",
    category: "Comidas",
    emoji: "🌯",
    price: 110,
    stock: 25,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 380, protein: 34, minutes: 10, tags: ["Rápidas", "Bajo en Carbos"] },
    photoQuery: "turkey wrap healthy",
  },
  {
    id: "m6",
    sku: "MEAL-HUEV",
    barcode: "7501000000141",
    name: "Omelette Proteico",
    category: "Comidas",
    emoji: "🍳",
    price: 95,
    stock: 30,
    minStock: 8,
    channels: ["online"],
    mealInfo: { calories: 340, protein: 30, minutes: 8, tags: ["Rápidas", "30g+ Proteína"] },
    photoQuery: "protein omelette",
  },
  {
    id: "m7",
    sku: "MEAL-CAMA",
    barcode: "7501000000158",
    name: "Camarones al Ajillo Fit",
    category: "Comidas",
    emoji: "🍤",
    price: 175,
    stock: 3,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 430, protein: 40, minutes: 16, tags: ["Bajo en Carbos", "30g+ Proteína"] },
    photoQuery: "garlic shrimp healthy",
  },
  {
    id: "m8",
    sku: "MEAL-PAST",
    barcode: "7501000000165",
    name: "Pasta Integral con Pollo",
    category: "Comidas",
    emoji: "🍝",
    price: 135,
    stock: 16,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 590, protein: 41, minutes: 15, tags: ["Post-Entreno"] },
    photoQuery: "whole wheat pasta chicken",
  },
  {
    id: "m9",
    sku: "MEAL-TOFU",
    barcode: "7501000000172",
    name: "Tofu Salteado Asiático",
    category: "Comidas",
    emoji: "🥢",
    price: 120,
    stock: 0,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 360, protein: 26, minutes: 14, tags: ["Vegano", "Bajo en Carbos"] },
    photoQuery: "tofu stir fry",
  },
  {
    id: "m10",
    sku: "MEAL-SOPA",
    barcode: "7501000000189",
    name: "Sopa de Lentejas Proteica",
    category: "Comidas",
    emoji: "🍲",
    price: 100,
    stock: 19,
    minStock: 5,
    channels: ["online"],
    mealInfo: { calories: 320, protein: 22, minutes: 20, tags: ["Vegano", "Rápidas"] },
    photoQuery: "lentil soup",
  },
];

export const SHIPPING_COST = 99;

export const DEFAULT_CUSTOMER = {
  nombre: "Ana García",
  telefono: "55 1234 5678",
  correo: "ana.garcia@example.com",
  direccion: "Av. Insurgentes Sur 123, CDMX",
};
